language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --no-progress
  - php bin/cli.php install --environment ci
  - cd $TRAVIS_BUILD_DIR

script:
  - composer check-all

