theme: jekyll-theme-cayman

# Name of your site (displayed in the header)
name: Prisma

# Name of website (site.title)
title: Prisma

# Short description of your site
description: A Slim Framework 3 example application